# Generated by Django 5.1.6 on 2025-02-26 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfilproyecto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilproyecto',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.grupo'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='miembros',
            field=models.ManyToManyField(blank=True, related_name='grupos', to=settings.AUTH_USER_MODEL),
        ),
    ]
